//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.30 at 11:23:24 AM EST 
//


package gov.nist.healthcare.cds.domain.xml.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EvaluationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EvaluationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Vaccine" type="{http://www.example.org/testCase/}VaccineType"/>
 *         &lt;element name="EvaluationReason" type="{http://www.example.org/testCase/}EvaluationReasonType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="status" use="required" type="{http://www.example.org/testCase/}statusType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EvaluationType", propOrder = {
    "vaccine",
    "evaluationReason"
})
public class EvaluationType {

    @XmlElement(name = "Vaccine", required = true)
    protected VaccineType vaccine;
    @XmlElement(name = "EvaluationReason")
    protected EvaluationReasonType evaluationReason;
    @XmlAttribute(name = "status", required = true)
    protected StatusType status;

    /**
     * Gets the value of the vaccine property.
     * 
     * @return
     *     possible object is
     *     {@link VaccineType }
     *     
     */
    public VaccineType getVaccine() {
        return vaccine;
    }

    /**
     * Sets the value of the vaccine property.
     * 
     * @param value
     *     allowed object is
     *     {@link VaccineType }
     *     
     */
    public void setVaccine(VaccineType value) {
        this.vaccine = value;
    }

    /**
     * Gets the value of the evaluationReason property.
     * 
     * @return
     *     possible object is
     *     {@link EvaluationReasonType }
     *     
     */
    public EvaluationReasonType getEvaluationReason() {
        return evaluationReason;
    }

    /**
     * Sets the value of the evaluationReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link EvaluationReasonType }
     *     
     */
    public void setEvaluationReason(EvaluationReasonType value) {
        this.evaluationReason = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setStatus(StatusType value) {
        this.status = value;
    }

}
