//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.02 at 09:33:03 PM EDT 
//


package gov.nist.healthcare.cds.domain.xml.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nist.healthcare.cds.domain.xml.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ValidationReport_QNAME = new QName("http://www.example.org/testCase/", "ValidationReport");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nist.healthcare.cds.domain.xml.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ValidationReport }
     * 
     */
    public ValidationReport createValidationReport() {
        return new ValidationReport();
    }

    /**
     * Create an instance of {@link TestCase }
     * 
     */
    public TestCase createTestCase() {
        return new TestCase();
    }

    /**
     * Create an instance of {@link DateType }
     * 
     */
    public DateType createDateType() {
        return new DateType();
    }

    /**
     * Create an instance of {@link MetaDataType }
     * 
     */
    public MetaDataType createMetaDataType() {
        return new MetaDataType();
    }

    /**
     * Create an instance of {@link PatientType }
     * 
     */
    public PatientType createPatientType() {
        return new PatientType();
    }

    /**
     * Create an instance of {@link EventsType }
     * 
     */
    public EventsType createEventsType() {
        return new EventsType();
    }

    /**
     * Create an instance of {@link ForecastsType }
     * 
     */
    public ForecastsType createForecastsType() {
        return new ForecastsType();
    }

    /**
     * Create an instance of {@link SummaryType }
     * 
     */
    public SummaryType createSummaryType() {
        return new SummaryType();
    }

    /**
     * Create an instance of {@link DoseValidationType }
     * 
     */
    public DoseValidationType createDoseValidationType() {
        return new DoseValidationType();
    }

    /**
     * Create an instance of {@link ReportSummaryType }
     * 
     */
    public ReportSummaryType createReportSummaryType() {
        return new ReportSummaryType();
    }

    /**
     * Create an instance of {@link VaccineType }
     * 
     */
    public VaccineType createVaccineType() {
        return new VaccineType();
    }

    /**
     * Create an instance of {@link RelativeToType }
     * 
     */
    public RelativeToType createRelativeToType() {
        return new RelativeToType();
    }

    /**
     * Create an instance of {@link RelativeDateType }
     * 
     */
    public RelativeDateType createRelativeDateType() {
        return new RelativeDateType();
    }

    /**
     * Create an instance of {@link ValidationResultType }
     * 
     */
    public ValidationResultType createValidationResultType() {
        return new ValidationResultType();
    }

    /**
     * Create an instance of {@link TestCaseMetaDataType }
     * 
     */
    public TestCaseMetaDataType createTestCaseMetaDataType() {
        return new TestCaseMetaDataType();
    }

    /**
     * Create an instance of {@link FixedDateType }
     * 
     */
    public FixedDateType createFixedDateType() {
        return new FixedDateType();
    }

    /**
     * Create an instance of {@link ForecastsReportType }
     * 
     */
    public ForecastsReportType createForecastsReportType() {
        return new ForecastsReportType();
    }

    /**
     * Create an instance of {@link DateValidationType }
     * 
     */
    public DateValidationType createDateValidationType() {
        return new DateValidationType();
    }

    /**
     * Create an instance of {@link EvaluationReasonType }
     * 
     */
    public EvaluationReasonType createEvaluationReasonType() {
        return new EvaluationReasonType();
    }

    /**
     * Create an instance of {@link ForecastValidationType }
     * 
     */
    public ForecastValidationType createForecastValidationType() {
        return new ForecastValidationType();
    }

    /**
     * Create an instance of {@link SoftwareConfigType }
     * 
     */
    public SoftwareConfigType createSoftwareConfigType() {
        return new SoftwareConfigType();
    }

    /**
     * Create an instance of {@link EvaluationsReportType }
     * 
     */
    public EvaluationsReportType createEvaluationsReportType() {
        return new EvaluationsReportType();
    }

    /**
     * Create an instance of {@link EventValidationType }
     * 
     */
    public EventValidationType createEventValidationType() {
        return new EventValidationType();
    }

    /**
     * Create an instance of {@link RuleType }
     * 
     */
    public RuleType createRuleType() {
        return new RuleType();
    }

    /**
     * Create an instance of {@link VaccinationEventReportType }
     * 
     */
    public VaccinationEventReportType createVaccinationEventReportType() {
        return new VaccinationEventReportType();
    }

    /**
     * Create an instance of {@link ForecastType }
     * 
     */
    public ForecastType createForecastType() {
        return new ForecastType();
    }

    /**
     * Create an instance of {@link SerieStatusType }
     * 
     */
    public SerieStatusType createSerieStatusType() {
        return new SerieStatusType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link ReportMetaDataType }
     * 
     */
    public ReportMetaDataType createReportMetaDataType() {
        return new ReportMetaDataType();
    }

    /**
     * Create an instance of {@link EvaluationsType }
     * 
     */
    public EvaluationsType createEvaluationsType() {
        return new EvaluationsType();
    }

    /**
     * Create an instance of {@link PatientTypeReport }
     * 
     */
    public PatientTypeReport createPatientTypeReport() {
        return new PatientTypeReport();
    }

    /**
     * Create an instance of {@link EvaluationValidationType }
     * 
     */
    public EvaluationValidationType createEvaluationValidationType() {
        return new EvaluationValidationType();
    }

    /**
     * Create an instance of {@link TestCaseInformationType }
     * 
     */
    public TestCaseInformationType createTestCaseInformationType() {
        return new TestCaseInformationType();
    }

    /**
     * Create an instance of {@link EvaluationsValidationType }
     * 
     */
    public EvaluationsValidationType createEvaluationsValidationType() {
        return new EvaluationsValidationType();
    }

    /**
     * Create an instance of {@link EvaluationType }
     * 
     */
    public EvaluationType createEvaluationType() {
        return new EvaluationType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidationReport }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/testCase/", name = "ValidationReport")
    public JAXBElement<ValidationReport> createValidationReport(ValidationReport value) {
        return new JAXBElement<ValidationReport>(_ValidationReport_QNAME, ValidationReport.class, null, value);
    }

}
