//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.30 at 11:23:24 AM EST 
//


package gov.nist.healthcare.cds.domain.xml.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nist.healthcare.cds.domain.xml.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nist.healthcare.cds.domain.xml.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestCase }
     * 
     */
    public TestCase createTestCase() {
        return new TestCase();
    }

    /**
     * Create an instance of {@link DateType }
     * 
     */
    public DateType createDateType() {
        return new DateType();
    }

    /**
     * Create an instance of {@link MetaDataType }
     * 
     */
    public MetaDataType createMetaDataType() {
        return new MetaDataType();
    }

    /**
     * Create an instance of {@link PatientType }
     * 
     */
    public PatientType createPatientType() {
        return new PatientType();
    }

    /**
     * Create an instance of {@link EventsType }
     * 
     */
    public EventsType createEventsType() {
        return new EventsType();
    }

    /**
     * Create an instance of {@link ForecastsType }
     * 
     */
    public ForecastsType createForecastsType() {
        return new ForecastsType();
    }

    /**
     * Create an instance of {@link SerieStatusType }
     * 
     */
    public SerieStatusType createSerieStatusType() {
        return new SerieStatusType();
    }

    /**
     * Create an instance of {@link VaccineType }
     * 
     */
    public VaccineType createVaccineType() {
        return new VaccineType();
    }

    /**
     * Create an instance of {@link ForecastType }
     * 
     */
    public ForecastType createForecastType() {
        return new ForecastType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link RelativeDateType }
     * 
     */
    public RelativeDateType createRelativeDateType() {
        return new RelativeDateType();
    }

    /**
     * Create an instance of {@link EvaluationsType }
     * 
     */
    public EvaluationsType createEvaluationsType() {
        return new EvaluationsType();
    }

    /**
     * Create an instance of {@link FixedDateType }
     * 
     */
    public FixedDateType createFixedDateType() {
        return new FixedDateType();
    }

    /**
     * Create an instance of {@link EvaluationReasonType }
     * 
     */
    public EvaluationReasonType createEvaluationReasonType() {
        return new EvaluationReasonType();
    }

    /**
     * Create an instance of {@link EvaluationType }
     * 
     */
    public EvaluationType createEvaluationType() {
        return new EvaluationType();
    }

}
