//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.02 at 11:39:19 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/testCase/")
package gov.nist.healthcare.cds.domain.xml.beans;
