//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.12 at 01:34:29 PM EDT 
//


package gov.nist.healthcare.cds.domain.xml.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ReportMetaDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportMetaDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DateExecuted" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Software" type="{https://fits.nist.gov/xml/}SoftwareConfigType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportMetaDataType", propOrder = {
    "dateExecuted",
    "software"
})
public class ReportMetaDataType {

    @XmlElement(name = "DateExecuted", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateExecuted;
    @XmlElement(name = "Software", required = true)
    protected SoftwareConfigType software;

    /**
     * Gets the value of the dateExecuted property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateExecuted() {
        return dateExecuted;
    }

    /**
     * Sets the value of the dateExecuted property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateExecuted(XMLGregorianCalendar value) {
        this.dateExecuted = value;
    }

    /**
     * Gets the value of the software property.
     * 
     * @return
     *     possible object is
     *     {@link SoftwareConfigType }
     *     
     */
    public SoftwareConfigType getSoftware() {
        return software;
    }

    /**
     * Sets the value of the software property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoftwareConfigType }
     *     
     */
    public void setSoftware(SoftwareConfigType value) {
        this.software = value;
    }

}
