//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 10:27:54 AM EDT 
//


package gov.nist.healthcare.cds.domain.xml.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VaccineMatcherType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VaccineMatcherType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VaccineMapping" type="{http://fits.nist.gov/vaccine_matcher/}VaccineMappingType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="matchSameGroup" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VaccineMatcherType", propOrder = {
    "vaccineMapping"
})
public class VaccineMatcherType {

    @XmlElement(name = "VaccineMapping", required = true)
    protected VaccineMappingType vaccineMapping;
    @XmlAttribute(name = "matchSameGroup")
    protected Boolean matchSameGroup;

    /**
     * Gets the value of the vaccineMapping property.
     * 
     * @return
     *     possible object is
     *     {@link VaccineMappingType }
     *     
     */
    public VaccineMappingType getVaccineMapping() {
        return vaccineMapping;
    }

    /**
     * Sets the value of the vaccineMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link VaccineMappingType }
     *     
     */
    public void setVaccineMapping(VaccineMappingType value) {
        this.vaccineMapping = value;
    }

    /**
     * Gets the value of the matchSameGroup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMatchSameGroup() {
        return matchSameGroup;
    }

    /**
     * Sets the value of the matchSameGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMatchSameGroup(Boolean value) {
        this.matchSameGroup = value;
    }

}
