//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.01 at 04:16:03 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://fits.nist.gov/vaccine_matcher/")
package gov.nist.healthcare.cds.service.domain.matcher;
